services:
  app:
    image: bitnami/php-fpm:8.4.8
    container_name: magento_app
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini:/opt/bitnami/php/etc/php.ini
    depends_on:
      - db
      - opensearch
      - valkey
    networks:
      - magento

  web:
    image: nginx:1.26.3-alpine
    container_name: magento_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - magento

  db:
    image: mysql:8.4.5
    container_name: magento_db
    environment:
      MYSQL_ROOT_PASSWORD: r00tP@ssw0rd
      MYSQL_DATABASE: magento
      MYSQL_USER: magento_user
      MYSQL_PASSWORD: magento_password
    ports:
      - "3306:3306"
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - dbdata:/var/lib/mysql
    networks:
      - magento

  opensearch:
    image: opensearchproject/opensearch:2.19.0
    container_name: magento_opensearch
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=0penSearchPassw0rd
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
      ## Uncomment to set custom heap size to avoid memory errors
      #- "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      ## Uncomment to increase the virtual memory map count
      #- "max_map_count=262144"
    ports:
      - "9200:9200"
    networks:
      - magento
    
  valkey:  
    image: bitnami/valkey:8.0.2
    container_name: magento_valkey
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379" 
    networks:
      - magento

volumes:
  dbdata:

networks:
  magento:
    driver: bridge
