# Makefile

APP_CONTAINER=magento_app
DB_CONTAINER=magento_db

INSTALL_SCRIPT=bin/install.sh
RUN_SCRIPT=bin/run.sh
CREATE_PROJECT_SCRIPT=bin/create-project.sh
SETUP_DB_SCRIPT=bin/setup-db.sh
SETUP_MAGENTO_SCRIPT=bin/setup-magento.sh

install:
	chmod +x $(INSTALL_SCRIPT) $(RUN_SCRIPT) $(SETUP_DB_SCRIPT) $(SETUP_MAGENTO_SCRIPT) $(CREATE_PROJECT_SCRIPT)
	APP_CONTAINER=$(APP_CONTAINER) \
	DB_CONTAINER=$(DB_CONTAINER) \
	RUN_SCRIPT=$(RUN_SCRIPT) \
	SETUP_DB_SCRIPT=$(SETUP_DB_SCRIPT) \
	SETUP_MAGENTO_SCRIPT=$(SETUP_MAGENTO_SCRIPT) \
	CREATE_PROJECT_SCRIPT=$(CREATE_PROJECT_SCRIPT) \
	./$(INSTALL_SCRIPT)

start:
	chmod +x $(RUN_SCRIPT)
	APP_CONTAINER=$(APP_CONTAINER) ./$(RUN_SCRIPT)

stop:
	docker-compose down
